"use client";

import { useState, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileText,
  Link2,
  UploadCloud,
  Sparkles,
  Loader2,
  AlertCircle,
  CheckCircle2,
  X,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  BarChart3,
} from "lucide-react";

type InputMode = "pdf" | "url";

interface SummaryResult {
  summary: string;
  provider?: string;
  fileName?: string;
  fileSize?: number;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function SummaryDisplay({ result }: { result: SummaryResult }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(true);

  // Split into paragraphs for better readability
  const paragraphs = result.summary.split(/\n+/).filter((p) => p.trim().length > 0);
  const hasMore = paragraphs.length > 4;
  const displayedParagraphs = expanded ? paragraphs : paragraphs.slice(0, 3);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(result.summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="rounded-3xl border border-emerald-200 dark:border-emerald-800/60 bg-white dark:bg-zinc-900 overflow-hidden shadow-xl"
    >
      {/* Header bar */}
      <div className="flex items-center justify-between px-6 py-4 bg-emerald-50 dark:bg-emerald-900/20 border-b border-emerald-100 dark:border-emerald-800/60">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-emerald-600 text-white">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <p className="font-bold text-zinc-900 dark:text-white text-sm">
              AI Summary Generated
            </p>
            {result.fileName && (
              <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
                {result.fileName}
                {result.fileSize && ` · ${formatFileSize(result.fileSize)}`}
              </p>
            )}
          </div>
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 text-xs font-bold text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-white transition-colors"
        >
          {copied ? (
            <><Check className="w-3.5 h-3.5 text-emerald-500" /> Copied</>
          ) : (
            <><Copy className="w-3.5 h-3.5" /> Copy</>
          )}
        </button>
      </div>

      {/* Summary text */}
      <div className="px-6 py-6">
        <div className="space-y-4">
          {displayedParagraphs.map((para, i) => {
            const isTakeaway = para.toLowerCase().startsWith("investor takeaway");
            return (
              <p
                key={i}
                className={`leading-relaxed text-[15px] ${
                  isTakeaway
                    ? "font-semibold text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-900/20 rounded-2xl px-4 py-3 border border-indigo-100 dark:border-indigo-800/50"
                    : "text-zinc-700 dark:text-zinc-300"
                }`}
              >
                {para}
              </p>
            );
          })}
        </div>

        {hasMore && (
          <button
            onClick={() => setExpanded(!expanded)}
            className="mt-4 flex items-center gap-1.5 text-sm font-bold text-indigo-600 dark:text-indigo-400 hover:underline"
          >
            {expanded ? (
              <><ChevronUp className="w-4 h-4" /> Show Less</>
            ) : (
              <><ChevronDown className="w-4 h-4" /> Show Full Summary ({paragraphs.length - 3} more paragraphs)</>
            )}
          </button>
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-3 bg-zinc-50 dark:bg-zinc-800/50 border-t border-zinc-100 dark:border-zinc-800 flex items-center gap-2">
        <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
        <p className="text-xs text-zinc-500 dark:text-zinc-400 font-medium">
          {result.provider ? `Generated by ${result.provider}` : "AI Generated"} · StockRecord AI · For educational purposes only
        </p>
      </div>
    </motion.div>
  );
}

export default function ReportSummarizerPage() {
  const [mode, setMode] = useState<InputMode>("pdf");
  const [url, setUrl] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<SummaryResult | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileDrop = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const dropped = e.dataTransfer.files?.[0];
    if (dropped?.type === "application/pdf") {
      setFile(dropped);
      setError(null);
    } else {
      setError("Only PDF files are supported.");
    }
  }, []);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected?.type === "application/pdf") {
      setFile(selected);
      setError(null);
    } else {
      setError("Only PDF files are supported.");
    }
  };

  const handleSubmit = async () => {
    setError(null);
    setResult(null);
    setIsLoading(true);

    try {
      if (mode === "url") {
        if (!url.trim()) {
          setError("Please enter a valid URL.");
          setIsLoading(false);
          return;
        }

        const res = await fetch("/api/summarize", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: url.trim() }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "Failed to summarize.");
        setResult(data);
      } else {
        if (!file) {
          setError("Please upload a PDF file.");
          setIsLoading(false);
          return;
        }

        const formData = new FormData();
        formData.append("file", file);

        const res = await fetch("/api/summarize", {
          method: "POST",
          body: formData,
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "Failed to summarize.");
        setResult(data);
      }
    } catch (err: any) {
      setError(err.message || "Something went wrong.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      {/* Background Decor */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none -z-10">
        <div className="absolute top-[-10%] right-[-10%] w-[50%] h-[50%] bg-violet-500/5 blur-[120px] rounded-full" />
        <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] bg-emerald-500/5 blur-[120px] rounded-full" />
      </div>

      <div className="max-w-4xl space-y-8">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <div className="p-2 rounded-xl bg-violet-600 text-white">
                <FileText className="w-5 h-5" />
              </div>
              <h1 className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight">
                Report <span className="text-violet-600 dark:text-violet-400">Summarizer</span>
              </h1>
            </div>
            <p className="text-sm text-zinc-500 dark:text-zinc-400 ml-12">
              Upload any document and get an instant AI summary of the key facts and numbers.
            </p>
          </div>
          <span className="ml-12 sm:ml-0 flex items-center gap-1.5 text-[10px] font-bold px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-400">
            <Sparkles className="w-3 h-3" /> Groq + Gemini
          </span>
        </div>

        {/* Input Mode Tabs */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="flex gap-2 p-1.5 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl w-fit"
        >
          <button
            onClick={() => { setMode("pdf"); setError(null); setResult(null); }}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${
              mode === "pdf"
                ? "bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 shadow"
                : "text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white"
            }`}
          >
            <UploadCloud className="w-4 h-4" />
            Upload PDF
          </button>
          <button
            onClick={() => { setMode("url"); setError(null); setResult(null); }}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${
              mode === "url"
                ? "bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 shadow"
                : "text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white"
            }`}
          >
            <Link2 className="w-4 h-4" />
            Paste URL
          </button>
        </motion.div>

        {/* Input Area */}
        <AnimatePresence mode="wait">
          {mode === "pdf" ? (
            <motion.div
              key="pdf"
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
            >
              <div
                onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={handleFileDrop}
                onClick={() => fileInputRef.current?.click()}
                className={`relative cursor-pointer rounded-3xl border-2 border-dashed p-10 text-center transition-all duration-200 ${
                  isDragging
                    ? "border-violet-500 bg-violet-50 dark:bg-violet-900/10"
                    : file
                    ? "border-emerald-400 bg-emerald-50 dark:bg-emerald-900/10"
                    : "border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 hover:border-violet-400 hover:bg-violet-50/50 dark:hover:bg-violet-900/5"
                }`}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="application/pdf"
                  className="hidden"
                  onChange={handleFileSelect}
                />

                {file ? (
                  <div className="flex flex-col items-center gap-3">
                    <div className="w-16 h-16 rounded-2xl bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
                      <FileText className="w-8 h-8 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    <div>
                      <p className="font-bold text-zinc-900 dark:text-white">{file.name}</p>
                      <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-0.5">{formatFileSize(file.size)}</p>
                    </div>
                    <button
                      onClick={(e) => { e.stopPropagation(); setFile(null); }}
                      className="flex items-center gap-1 text-xs font-bold text-red-500 hover:text-red-700 mt-1"
                    >
                      <X className="w-3.5 h-3.5" /> Remove
                    </button>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-4">
                    <div className="w-16 h-16 rounded-2xl bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center">
                      <UploadCloud className="w-8 h-8 text-zinc-400" />
                    </div>
                    <div>
                      <p className="font-bold text-zinc-900 dark:text-white text-lg">
                        Drag & drop your PDF here
                      </p>
                      <p className="text-zinc-500 dark:text-zinc-400 text-sm mt-1">
                        or click to browse · Max 20 MB · PDFs and text-heavy documents supported
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="url"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="space-y-3"
            >
              <label className="block text-sm font-bold text-zinc-700 dark:text-zinc-300">
                Document URL
              </label>
              <div className="relative group">
                <Link2 className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-400 group-focus-within:text-violet-500 transition-colors" />
                <input
                  type="url"
                  placeholder="https://example.com/annual-report.pdf or earnings-page-url"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
                  className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-500 transition-all font-medium text-zinc-900 dark:text-zinc-100 text-sm"
                />
              </div>
              <p className="text-xs text-zinc-400 dark:text-zinc-500 font-medium">
                Supports direct PDF links and HTML pages (e.g., company investor pages, MoneyControl earnings pages).
              </p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Error */}
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-3 px-4 py-3 rounded-2xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/60 text-red-700 dark:text-red-400"
            >
              <AlertCircle className="w-5 h-5 shrink-0" />
              <p className="text-sm font-medium">{error}</p>
              <button onClick={() => setError(null)} className="ml-auto">
                <X className="w-4 h-4" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Submit Button */}
        <motion.button
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          onClick={handleSubmit}
          disabled={isLoading || (mode === "pdf" ? !file : !url.trim())}
          whileHover={{ scale: isLoading ? 1 : 1.02 }}
          whileTap={{ scale: isLoading ? 1 : 0.98 }}
          className={`w-full flex items-center justify-center gap-3 py-4 rounded-2xl font-bold text-base transition-all shadow-lg ${
            isLoading || (mode === "pdf" ? !file : !url.trim())
              ? "bg-zinc-200 dark:bg-zinc-800 text-zinc-400 cursor-not-allowed shadow-none"
              : "bg-violet-600 hover:bg-violet-700 text-white shadow-violet-500/25 hover:shadow-xl hover:shadow-violet-500/30"
          }`}
        >
          {isLoading ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              Analysing document with AI…
            </>
          ) : (
            <>
              <BarChart3 className="w-5 h-5" />
              Generate Financial Summary
            </>
          )}
        </motion.button>

        {/* Loading indicator */}
        <AnimatePresence>
          {isLoading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-8"
            >
              <div className="flex flex-col items-center gap-4 text-center">
                <div className="relative w-16 h-16">
                  <div className="absolute inset-0 rounded-full border-4 border-violet-100 dark:border-violet-900/30" />
                  <div className="absolute inset-0 rounded-full border-4 border-t-violet-600 animate-spin" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <Sparkles className="w-6 h-6 text-violet-600" />
                  </div>
                </div>
                <div>
                  <p className="font-bold text-zinc-900 dark:text-white">AI is reading your document…</p>
                  <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
                    Extracting text and summarising. Large documents may take up to 30 seconds.
                  </p>
                </div>
                <div className="w-full bg-zinc-100 dark:bg-zinc-800 rounded-full h-1.5 overflow-hidden">
                  <div className="h-full bg-violet-500 rounded-full animate-pulse w-3/4" />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Result */}
        <AnimatePresence>
          {result && !isLoading && <SummaryDisplay result={result} />}
        </AnimatePresence>

        {/* Sample reports hint */}
        {!result && !isLoading && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4 }}
            className="rounded-2xl bg-zinc-100/60 dark:bg-zinc-900/60 border border-zinc-200 dark:border-zinc-800 p-5"
          >
            <p className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5" /> Try these sample documents
            </p>
            <div className="space-y-2">
              {[
                { label: "Reliance Industries Annual Report 2023–24", url: "https://www.ril.com/getattachment/ril-ar-fy2024.pdf" },
                { label: "TCS Q4 FY2024 Earnings Press Release", url: "https://www.tcs.com/content/dam/tcs-btp/pdf/media/q4fy24-press-release.pdf" },
                { label: "HDFC Bank Annual Report 2024", url: "https://www.hdfcbank.com/content/bbp/repositories/723fb80a-2dde-42a3-9793-7ae1be57c87f.pdf" },
              ].map((sample) => (
                <button
                  key={sample.label}
                  onClick={() => { setMode("url"); setUrl(sample.url); }}
                  className="block w-full text-left px-3 py-2 rounded-xl hover:bg-white dark:hover:bg-zinc-800 transition-colors"
                >
                  <span className="text-xs text-zinc-600 dark:text-zinc-300 font-medium">→ {sample.label}</span>
                </button>
              ))}
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}
